### ISSUE TITLE
vue文件中字符串及箭头符号高亮异常

### ISSUE THREAD

**Issue by cuichaoyu** [xsun12131/HighlightBracketPair#1]
vue文件中，有些情况下高亮异常，效果如图
![QQ截图20210912112338](https://user-images.githubusercontent.com/42434285/132970951-cefaa5cd-0680-4a1a-9f0b-b2e771f8dd5b.png)
![QQ截图20210912112347](https://user-images.githubusercontent.com/42434285/132970952-c4523743-9d3d-4322-a628-bfa64389c6c3.png)
![QQ截图20210912112407](https://user-images.githubusercontent.com/42434285/132970953-0898ada0-a450-4a6e-8b84-228d83a2ea33.png)
![QQ截图20210912112437](https://user-images.githubusercontent.com/42434285/132970955-f300e580-484d-4ef8-a21c-32c07b96781b.png)
![QQ截图20210912112455](https://user-images.githubusercontent.com/42434285/132970957-728052d1-f820-47c3-94a6-52d30ac35b3a.png)

**Comment by xsun12131** [comment]
`我的想法就是如图这样高亮，<p>...</p>高亮这个标签，<p....../>只高亮 ”<" 和 “/>"
你有什么好的想法吗？`

**Comment by cuichaoyu** [comment]
插件最开始的意义就是高亮这些符号，当然高亮所在标签也可以成为你这个项目的亮点，所以了，如果情况允许，可以配置化。不知道你fork这个项目的初衷是什么，如果是简单的正常使用，那么现在的这种机制也还可以，当然这种机制还有bug在，如果说你是要二次开发，迭代功能的话，那么高亮符号和高亮标签都可以保留。
我个人来讲，喜欢高亮符号，因为高亮整个标签的话，样式有些突兀，可能是配色的问题，这个你可以测试一下；


另外对bug来说，怎么高亮的不一样，上面高亮标签，下面高亮符号了

**Comment by xsun12131** [comment]
> 插件最开始的意义就是高亮这些符号，当然高亮所在标签也可以成为你这个项目的亮点，所以了，如果情况允许，可以配置化。不知道你fork这个项目的初衷是什么，如果是简单的正常使用，那么现在的这种机制也还可以，当然这种机制还有bug在，如果说你是要二次开发，迭代功能的话，那么高亮符号和高亮标签都可以保留。 我个人来讲，喜欢高亮符号，因为高亮整个标签的话，样式有些突兀，可能是配色的问题，这个你可以测试一下； 另外对bug来说，怎么高亮的不一样，上面高亮标签，下面高亮符号了

本来是想此插件正常使用，看到你的回复得知还有其他bug想着帮忙修改一下。
至于高亮所在标签，原项目就原本是有高亮标签的想法的，因为我在原项目中发现了这张xml配置图
![image](https://user-images.githubusercontent.com/43137453/132973613-9d0fab08-8922-4376-b833-50727570a45f.png)

但是项目介绍上并没有这张图。
高亮的不一样的问题：你发的图中，不一样的是图2，其他的都是高亮一样的。对于图2来说高亮标签的话会整个标签块，所以我做了修改。

**Comment by cuichaoyu** [comment]
所以说，你那边是既可以高亮符号，也可以高亮标签，代码上都是可行的是吧？你已经都实现了是吧？

**Comment by xsun12131** [comment]
> 所以说，你那边是既可以高亮符号，也可以高亮标签，代码上都是可行的是吧？你已经都实现了是吧？

对的，现在修改为都只高亮标签名了，可以试下新的版本，已经放在了Releases上。

**Comment by cuichaoyu** [comment]
我自己稍微调整下箭头符号配色，用起来真的挺不错的。
![QQ截图20210912152827](https://user-images.githubusercontent.com/42434285/132977832-30d2f2ce-9b2e-44a8-8271-6d55a8bc5c87.png)

**Comment by cuichaoyu** [comment]
另外有个问题，标签内的 小括号正常，中括号和
![QQ截图20210912153202](https://user-images.githubusercontent.com/42434285/132977891-7266fce1-6fba-4616-8516-cdbe514a00af.png)
![QQ截图20210912153211](https://user-images.githubusercontent.com/42434285/132977894-8bcb0642-8548-4b26-bcba-96f78b6ae78b.png)
![QQ截图20210912153226](https://user-images.githubusercontent.com/42434285/132977895-a8a6cf2e-f625-4fdc-ad8b-2ba2e2a20a9c.png)
大括号 没识别到

**Comment by xsun12131** [comment]
新增了标签内的识别，试试吧。因为和原本的括号识别是不一样的识别方式，所以为beta版。

**Comment by cuichaoyu** [comment]
挺好的，老哥，可以发市场了
